version: "2"
services:
  app:
    container_name: node-rest
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/moviedb
      - MONGODBTEST_URI=mongodb://mongo:27017/moviedbtest
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
